apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: kratix-github-access
spec:
  target:
    name: default-git-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: "10s"
  data:
    - remoteRef:
        key: ci-secrets
        property: GH_USERNAME
      secretKey: username
    - remoteRef:
        key: ci-secrets
        property: PERSONAL_ACCESS_TOKEN
      secretKey: password
